#!/usr/bin/env bash
set -e

BACKUP_DIR="$HOME/.config/backup/"

cd $BACKUP_DIR
git pull

rsync -av "$BACKUP_DIR/hypr/" "$HOME/.config/hypr/"
rsync -av "$BACKUP_DIR/waybar/" "$HOME/.config/waybar/"
rsync -av "$BACKUP_DIR/walker/" "$HOME/.config/walker/"
rsync -av "$BACKUP_DIR/elephant/" "$HOME/.config/elephant/"
rsync -av "$BACKUP_DIR/themes/aether/" "$HOME/.config/omarchy/themes/aether/"
mv "$BACKUP_DIR/starship.toml" "$HOME/.config/"
