#!/usr/bin/env bash
set -e

BACKUP_DIR="$HOME/.config/backup/"
TIMESTAMP="$(date +"%Y-%m-%d %H:%M:%S")"

mkdir -p "$BACKUP_DIR"

rsync -av --delete --exclude='shaders/' "$HOME/.config/hypr/" "$BACKUP_DIR/hypr/"
rsync -av --delete "$HOME/.config/waybar/" "$BACKUP_DIR/waybar/"
rsync -av --delete "$HOME/.config/walker/" "$BACKUP_DIR/walker/"
rsync -av --delete "$HOME/.config/elephant/" "$BACKUP_DIR/elephant/"

cd "$BACKUP_DIR"
git add .

if ! git diff --cached -quiet; then
    git commit -m "Backup $TIMESTAMP"
    git push
else
    echo "No changes to commit"
fi
