#!/usr/bin/env bash
set -e

BACKUP_DIR="$HOME/.config/backup/"

cd $BACKUP_DIR
git pull

rsync -av "$BACKUP_DIR/hypr/" "$HOME/.config/hypr/"
rsync -av "$BACKUP_DIR/waybar/" "$HOME/.config/waybar/"
rsync -av "$BACKUP_DIR/walker/" "$HOME/.config/walker/"
rsync -av "$BACKUP_DIR/elephant/" "$HOME/.config/elephant/"
mv "$BACKUP_DIR/starship.toml" "$HOME/.config/"
mv "$BACKUP_DIR/omarchy-cmd-screensaver" ~/.local/share/omarchy/bin/omarchy-cmd-screensaver
